AWSTemplateFormatVersion: '2010-09-09'
Description: >
  VPC with 2 Public + 2 Private Subnets, IGW, NAT, Route Tables, and Security Groups and Outputs.
Parameters:
  # VPC parameters first
  VpcName:
    Type: String
    Description: "Name of the VPC (e.g., MyVPC)"
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
    Description: "CIDR block for the VPC (e.g., 10.0.0.0/16)"
    AllowedPattern: '^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})\/(\d{1,2})$'
    ConstraintDescription: "Must be a valid IPv4 CIDR block format: x.x.x.x/y"
  # Subnet parameters next


Resources:
# VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref VpcName

Outputs: